# https://jupyterbook.org/en/stable/customize/config.html
name: quanttide-example-of-documentation
title: 量潮产品研发教程
author: 量潮科技
description: 介绍产品研发团队的协作方法
# Jupyter Book Config
only_build_toc_files: true